doctrine_migrations:
    dir_name: '%kernel.project_dir%/migrations'
    # namespace is arbitrary but should be different from App\migrations
    # as migrations classes should NOT be autoloaded
    namespace: DoctrineMigrations
